---
# This playbook deploys the server

- name: Deployment playbook
  gather_facts: false
  hosts: localhost
  connection: local 
  user: dfang

  tasks:
  - name: Print message
    debug:
      msg: Hello world
      
  - name: scp
    shell: sshpass -p 'ubuntu' scp ./spring-petclinic/target/spring-petclinic-3.1.0-SNAPSHOT.jar root@172.17.0.3:/
    register: ps
    ignore_errors: true

  - debug: var=ps.stdout_lines
