---
# This playbook deploys the server

- name: Deployment playbook
  gather_facts: false
  hosts: localhost
  connection: local 
  user: dfang

  tasks:
  - name: Print message
    debug:
      msg: Hello world
      
  - name: scp jar artifact
    shell: sshpass -p 'ubuntu' scp -o StrictHostKeyChecking=no ./spring-petclinic/target/spring-petclinic-3.1.0-SNAPSHOT.jar root@172.17.0.3:/ 
    register: ps
    ignore_errors: true
    
  - name: ssh to send start server command
    shell: sshpass -p 'ubuntu' ssh -o StrictHostKeyChecking=no root@172.17.0.3 'java /spring-petclinic-3.1.0-SNAPSHOT.jar --server.port=8082'
    register: ps
    ignore_errors: true

  - debug: var=ps.stdout_lines
